GET http://localhost:8083/hello
Accept: application/json

###

POST http://localhost:8083/hello/post
Content-Type: application/x-www-form-urlencoded

name=TEST8

###

GET http://localhost:8083/test/list

###
